"""
Calculate grain boundary energies from MLIP-relaxed GB structures.

Reads the JSON output files produced by MCP relax_structure calls on the
grain boundary supercells generated by create_grain_boundary.py, applies
the GB energy formula, and outputs a table and plot of γ_GB vs. misorientation
angle.

Formula:
    γ_GB = (E_GB - N × E_bulk) / (2 × A)

where E_GB is the total MLIP energy of the relaxed GB supercell, N is the
number of atoms, E_bulk is the bulk energy per atom (in eV), and A is the
cross-sectional interfacial area (Å²). The result is converted to J/m².

Usage:
    python calculate_gb_energy.py \
        --bulk-energy-per-atom -3.73 \
        --gb-relaxation-dir gb_relaxations/ \
        --output-dir gb_results/

Requirements:
    - Conda environment: base-agent
    - Required packages: pymatgen, numpy, matplotlib
"""

import argparse
import csv
import json
import logging
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../../"))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from src.utils.research_utils import get_current_research_dir

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger("GBEnergy")

# Conversion: eV/Å² → J/m²
EV_PER_A2_TO_J_PER_M2 = 16.0218


def parse_relax_result(json_path: Path) -> Optional[Dict]:
    """Extract total energy, n_atoms, and lattice from a relaxation result JSON.

    The MCP relax_structure tools write a JSON file with at minimum:
      {"final_energy": float, "n_atoms": int, "lattice": {"a": ..., "b": ...}}
    or the pymatgen Structure as_dict() nested inside.
    Returns None if the required fields cannot be found.
    """
    with open(json_path) as f:
        data = json.load(f)

    # Try direct fields first (MCP output format)
    energy = data.get("final_energy") or data.get("energy") or data.get("total_energy")
    n_atoms = data.get("n_atoms") or data.get("natoms")
    lattice = data.get("lattice", {})
    a = lattice.get("a") or lattice.get("matrix", [[None]])[0][0]
    b = lattice.get("b") or lattice.get("matrix", [[None, None]])[1][1] if lattice else None

    # Fallback: pymatgen Structure dict inside "final_structure"
    if energy is None:
        fs = data.get("final_structure", {})
        energy = fs.get("energy") or data.get("output", {}).get("energy")
        if "lattice" in fs:
            lp = fs["lattice"]
            a = lp.get("a")
            b = lp.get("b")
            n_atoms = len(fs.get("sites", []))

    if energy is None or n_atoms is None or a is None or b is None:
        return None

    return {"energy": float(energy), "n_atoms": int(n_atoms), "a": float(a), "b": float(b)}


def compute_gb_energy(
    e_gb: float,
    n_atoms: int,
    e_bulk_per_atom: float,
    area_A2: float,
) -> float:
    """Return grain boundary energy in J/m²."""
    delta_e = e_gb - n_atoms * e_bulk_per_atom  # eV
    gamma = delta_e / (2.0 * area_A2)           # eV/Å²
    return gamma * EV_PER_A2_TO_J_PER_M2        # J/m²


def load_metadata(relaxation_dir: Path) -> Optional[Dict]:
    """Try to load gb_structure_metadata.json from the structures directory."""
    # Common locations
    for candidate in [
        relaxation_dir / "gb_structure_metadata.json",
        relaxation_dir.parent / "gb_structures" / "gb_structure_metadata.json",
        relaxation_dir.parent / "gb_structure_metadata.json",
    ]:
        if candidate.exists():
            with open(candidate) as f:
                return json.load(f)
    return None


def plot_gb_energy(records: List[Dict], output_path: str, formula: str = "") -> None:
    """Plot grain boundary energy vs. misorientation angle."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({"font.size": 14})

    # Group by sigma for colour coding
    sigma_values = sorted(set(r.get("sigma", 0) for r in records))
    cmap = plt.cm.get_cmap("tab10", len(sigma_values))
    sigma_to_color = {s: cmap(i) for i, s in enumerate(sigma_values)}

    fig, ax = plt.subplots(figsize=(7, 5))

    for rec in sorted(records, key=lambda r: r["rotation_angle_deg"]):
        sigma = rec.get("sigma", 0)
        ax.scatter(
            rec["rotation_angle_deg"],
            rec["gb_energy_J_m2"],
            color=sigma_to_color[sigma],
            s=60,
            zorder=3,
            label=f"Σ{sigma}" if sigma not in [r.get("sigma") for r in records[:records.index(rec)]] else "",
        )

    # Connect points with a line
    sorted_recs = sorted(records, key=lambda r: r["rotation_angle_deg"])
    ax.plot(
        [r["rotation_angle_deg"] for r in sorted_recs],
        [r["gb_energy_J_m2"] for r in sorted_recs],
        color="gray",
        linewidth=1.5,
        linestyle="--",
        alpha=0.6,
        zorder=2,
    )

    ax.set_xlabel("Misorientation angle (°)", fontweight="bold")
    ax.set_ylabel("Grain boundary energy (J/m²)", fontweight="bold")
    title = f"Grain Boundary Energy — {formula}" if formula else "Grain Boundary Energy"
    ax.set_title(title)
    ax.grid(True, linestyle="--", alpha=0.6)
    ax.set_ylim(bottom=0)

    # Deduplicate legend
    handles, labels = ax.get_legend_handles_labels()
    seen = {}
    unique_handles, unique_labels = [], []
    for h, l in zip(handles, labels):
        if l not in seen:
            seen[l] = True
            unique_handles.append(h)
            unique_labels.append(l)
    ax.legend(unique_handles, unique_labels, frameon=False, fontsize=11, ncol=2)

    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.savefig(output_path.replace(".png", ".svg"), bbox_inches="tight")
    plt.close()
    logger.info(f"Saved GB energy plot to {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Calculate grain boundary energies from relaxed GB structures."
    )
    parser.add_argument(
        "--bulk-energy-per-atom",
        type=float,
        required=True,
        help="Bulk energy per atom in eV (from bulk relaxation output).",
    )
    parser.add_argument(
        "--gb-relaxation-dir",
        required=True,
        help="Directory containing JSON result files from MLIP GB relaxations.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory. Defaults to <research_dir>/gb_results.",
    )
    args = parser.parse_args()

    if args.output_dir is None:
        research_dir = get_current_research_dir()
        args.output_dir = str(research_dir / "gb_results")
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    relax_dir = Path(args.gb_relaxation_dir)
    if not relax_dir.exists():
        raise FileNotFoundError(f"Relaxation directory not found: {relax_dir}")

    # Try to load structure metadata for sigma/angle/area annotations
    metadata = load_metadata(relax_dir)
    meta_by_file: Dict[str, Dict] = {}
    if metadata:
        for entry in metadata.get("structures", []):
            meta_by_file[entry["cif_file"].replace(".cif", "")] = entry
        logger.info(f"Loaded GB structure metadata ({len(meta_by_file)} entries)")
    else:
        logger.warning(
            "gb_structure_metadata.json not found; sigma/angle annotations will be missing."
        )

    # Collect all JSON result files
    json_files = sorted(relax_dir.glob("*.json"))
    if not json_files:
        raise FileNotFoundError(f"No JSON files found in {relax_dir}")
    logger.info(f"Found {len(json_files)} relaxation result files")

    records = []
    failed = []

    for json_path in json_files:
        result = parse_relax_result(json_path)
        if result is None:
            logger.warning(f"Could not parse {json_path.name} — skipping")
            failed.append(json_path.name)
            continue

        area_A2 = result["a"] * result["b"]
        gb_energy = compute_gb_energy(
            e_gb=result["energy"],
            n_atoms=result["n_atoms"],
            e_bulk_per_atom=args.bulk_energy_per_atom,
            area_A2=area_A2,
        )

        # Match to structure metadata (strip common suffixes)
        stem = json_path.stem.replace("_relaxed", "").replace("_relax", "")
        meta = meta_by_file.get(stem, {})

        rec = {
            "filename": json_path.name,
            "sigma": meta.get("sigma", None),
            "rotation_angle_deg": meta.get("rotation_angle_deg", None),
            "rotation_axis": meta.get("rotation_axis", None),
            "n_atoms": result["n_atoms"],
            "total_energy_eV": round(result["energy"], 6),
            "interface_area_A2": round(area_A2, 4),
            "gb_energy_J_m2": round(gb_energy, 4),
        }
        records.append(rec)

        sigma_str = f"Σ{rec['sigma']}" if rec["sigma"] else "?"
        angle_str = f"{rec['rotation_angle_deg']:.2f}°" if rec["rotation_angle_deg"] else "?"
        logger.info(
            f"  {sigma_str:6s}  {angle_str:8s}  "
            f"γ_GB = {gb_energy:.4f} J/m²  "
            f"(A = {area_A2:.1f} Å²,  N = {result['n_atoms']} atoms)"
        )

    if not records:
        raise RuntimeError("No GB energies could be calculated from the provided data.")

    # Save JSON
    summary_path = output_dir / "gb_energy_results.json"
    with open(summary_path, "w") as f:
        json.dump(
            {
                "bulk_energy_per_atom_eV": args.bulk_energy_per_atom,
                "n_boundaries": len(records),
                "n_failed": len(failed),
                "failed_files": failed,
                "results": records,
            },
            f,
            indent=2,
        )
    logger.info(f"Saved GB energy results to {summary_path}")

    # Save CSV
    csv_path = output_dir / "gb_summary_table.csv"
    fieldnames = [
        "filename", "sigma", "rotation_angle_deg", "n_atoms",
        "total_energy_eV", "interface_area_A2", "gb_energy_J_m2",
    ]
    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(records)
    logger.info(f"Saved CSV table to {csv_path}")

    # Plot (only if we have angle information)
    records_with_angle = [r for r in records if r["rotation_angle_deg"] is not None]
    if records_with_angle:
        plot_path = str(output_dir / "gb_energy_vs_angle.png")
        plot_gb_energy(records_with_angle, plot_path)
    else:
        logger.warning("No misorientation angle data available; skipping plot.")

    # Summary table
    gb_energies = [r["gb_energy_J_m2"] for r in records]
    min_rec = min(records, key=lambda r: r["gb_energy_J_m2"])

    print("\n" + "=" * 60)
    print("GRAIN BOUNDARY ENERGY SUMMARY")
    print("=" * 60)
    print(f"  Boundaries calculated : {len(records)}")
    print(f"  Bulk E/atom (eV)      : {args.bulk_energy_per_atom}")
    print(f"  γ_GB range (J/m²)     : {min(gb_energies):.4f} – {max(gb_energies):.4f}")
    print(f"  Lowest energy GB      : Σ{min_rec['sigma']} at "
          f"{min_rec['rotation_angle_deg']:.2f}° → "
          f"γ = {min_rec['gb_energy_J_m2']:.4f} J/m²")
    print(f"  Results saved to      : {output_dir}")
    print("=" * 60)


if __name__ == "__main__":
    main()
